import clsx from "clsx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import { CategoryFilters } from "../components/CategoryFilters";
import { SearchForm } from "../components/SearchForm";
import { Sorters } from "../components/Sorters";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const SearchLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="grid gap-4 lg:gap-8">
      <div className="flex justify-center">
        <SearchForm />
      </div>
      <div className="grid grid-flow-row auto-rows-max lg:grid-cols-6 gap-8 grid-cols-4">
        <aside className="order-1 col-span-2 lg:col-span-1">
          <CategoryFilters />
        </aside>
        <main className="order-3 col-span-4 lg:col-span-4 lg:order-2">
          {children}
        </main>
        <aside className="order-2 col-span-2 lg:col-span-1 lg:order-3">
          <Sorters />
        </aside>
      </div>
    </div>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "bg-stone-50")}>
        <div className="mx-auto container my-4 px-4">
          <SearchLayout>{children}</SearchLayout>
        </div>
      </body>
    </html>
  );
}
